import type { Metadata } from "next";
import { Work_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import 'easymde/dist/easymde.min.css'
import { Toaster } from "@/components/ui/sonner";

const workSans = Work_Sans({
  variable: "--font-Work-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "YZ-Directory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${workSans.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
